name = "loop-gallery-space"
compatibility_date = "2024-11-01"
main = ".output/server/index.mjs"

[[d1_databases]]
binding = "loopgallery-db"
database_name = "loopgallery-db"
database_id = "9c338118-ec94-41bc-90d1-f58f1bde24c9"
migrations_dir = "server/database/migrations"

[[r2_buckets]]
binding = "loopgallery-media"
bucket_name = "loopgallery-media"

[vars]
# Set in Cloudflare Pages dashboard for production
